[features]
seeds = false
[programs.devnet]
tars_launch = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "https://metaplex.devnet.rpcpool.com/"
wallet = "/Users/bhargavveepuri/dev-solana-wallet/TARS3x6dnY9WtoKETWD63qTG61neaYnMeaDgVjwnrxp.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
